[tool.poetry]
name = "juggler"
version = "0.1.0"
description = ""
authors = ["Thiago Cardoso <thiagoncc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
textual = "^0.26.0"
guidance = "^0.0.57"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
